# Generated by Django 3.2.6 on 2021-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='fetured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
