# Generated by Django 3.2.6 on 2021-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='fetured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
