# Generated by Django 3.2.6 on 2021-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='fetured_image/%Y/%m/%d/'),
        ),
    ]
