# Generated by Django 3.2.6 on 2022-02-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cropping',
        ),
    ]
