# Generated by Django 3.2.6 on 2022-03-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_cropping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('email', 'post')},
        ),
    ]
